version: '3.8'

services:
  db:
    image: postgres:13
    restart: on-failure

    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    env_file:
      - .env

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d gma_task -U postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-network

    ports:
      - "5432:5432"

  # -----------------------------------------

  web:
    build: .
    restart: on-failure

    env_file:
      - .env

    depends_on:
      - db

    networks:
      - app-network

    ports:
      - "8000:8080"

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
